add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_bt_boat_details',
	'title' => 'Bateau — Détails',
	'fields' => array(
		array(
			'key' => 'field_bt_boat_tab_identity',
			'label' => 'Identité',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_bt_boat_tagline',
			'label' => 'Accroche courte',
			'name' => 'boat_tagline',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Ex: Le semi-rigide premium de la flotte',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_boat_description',
			'label' => 'Description',
			'name' => 'boat_description',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Description éditoriale complète du bateau',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_bt_boat_cover',
			'label' => 'Photo principale',
			'name' => 'boat_cover',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_bt_boat_gallery',
			'label' => 'Galerie photos',
			'name' => 'boat_gallery',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'insert' => 'append',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_bt_boat_video',
			'label' => 'URL Vidéo (YouTube / Vimeo)',
			'name' => 'boat_video',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_bt_boat_tab_specs',
			'label' => 'Caractéristiques techniques',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_bt_boat_length',
			'label' => 'Capitaine à bord',
			'name' => 'boat_captain',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Ex: 13,1',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_69ab0c256948a',
			'label' => 'Crew à disposition',
			'name' => 'boat_crew_number',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Ex: 13,1',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_boat_beam',
			'label' => 'Largeur (m)',
			'name' => 'boat_beam',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'boat_length',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_69abe98992957',
			'label' => 'Longueurs',
			'name' => 'boat_length',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'boat_thickness',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_bt_boat_engine',
			'label' => 'Motorisation',
			'name' => 'boat_enginepower',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => 'CV',
		),
		array(
			'key' => 'field_bt_boat_speed',
			'label' => 'Vitesse max',
			'name' => 'boat_speed',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Ex: 45 nœuds',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69ab039780c6c',
			'label' => 'Vitesse croisère',
			'name' => 'boat_cruising_speed',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Ex: 45 nœuds',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_boat_fuel',
			'label' => 'Carburant',
			'name' => 'boat_fuel',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'boat_fuel',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_69ab03c080c6d',
			'label' => 'Consommation carburant',
			'name' => 'boat_fuel_consumption',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => 'L/h',
		),
		array(
			'key' => 'field_bt_boat_year',
			'label' => 'Année',
			'name' => 'boat_year',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 1990,
			'max' => 2030,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_boat_tab_capacity',
			'label' => 'Capacité',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_bt_boat_pax_max',
			'label' => 'Passagers max (légal)',
			'name' => 'boat_pax_max',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Capacité légale maximale',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 1,
			'max' => 200,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'pax',
		),
		array(
			'key' => 'field_bt_boat_pax_comfort',
			'label' => 'Passagers confort optimal',
			'name' => 'boat_pax_comfort',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Recommandé pour le confort',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 1,
			'max' => 200,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'pax',
		),
		array(
			'key' => 'field_bt_boat_cabins',
			'label' => 'Cabines',
			'name' => 'boat_cabins',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'min' => 0,
			'max' => 20,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_boat_bathrooms',
			'label' => 'Salles de bain / WC',
			'name' => 'boat_bathrooms',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'min' => 0,
			'max' => 10,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_boat_tab_pricing',
			'label' => 'Tarification',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_bt_boat_price_half',
			'label' => 'Tarif demi-journée (€)',
			'name' => 'boat_price_half',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Laisser vide si non applicable',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 0,
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '€',
		),
		array(
			'key' => 'field_69ab050213831',
			'label' => 'Demi Journée	(nombre d\'heures)',
			'name' => 'boat_half_day_time',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 0,
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => 'h',
		),
		array(
			'key' => 'field_bt_boat_price_full',
			'label' => 'Tarif journée complète (€)',
			'name' => 'boat_price_full',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 0,
			'max' => '',
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => '€',
		),
		array(
			'key' => 'field_69ab048113830',
			'label' => 'Journée complète (nombre d\'heures)',
			'name' => 'boat_full_day_time',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 0,
			'max' => '',
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => 'h',
		),
		array(
			'key' => 'field_bt_boat_deposit',
			'label' => 'Caution (€)',
			'name' => 'boat_deposit',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 0,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '€',
			'max' => '',
		),
		array(
			'key' => 'field_bt_boat_price_note',
			'label' => 'Note tarifaire',
			'name' => 'boat_price_note',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'À partir de',
			'maxlength' => '',
			'placeholder' => 'à partir de..',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69ab0664062d9',
			'label' => 'Carburant inclus',
			'name' => 'boat_fuel_included',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
			'ui' => 1,
		),
		array(
			'key' => 'field_69ab17ffb304b',
			'label' => 'Tarifs par destination',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69ab1839de932',
			'label' => 'Tarifs à la sortie',
			'name' => 'boat_custom_price_by_departure',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_69ab183fde933',
					'label' => 'Zone de navigation',
					'name' => 'boat_navigation_zone',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'departure_city',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'checkbox',
					'bidirectional' => 0,
					'multiple' => 0,
					'allow_null' => 0,
					'bidirectional_target' => array(
					),
					'parent_repeater' => 'field_69ab1839de932',
				),
				array(
					'key' => 'field_69ab1859de934',
					'label' => 'Prix à la demi journée',
					'name' => 'boat_price_for_half_day',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '€ HT',
					'parent_repeater' => 'field_69ab1839de932',
				),
				array(
					'key' => 'field_69ab186bde935',
					'label' => 'Prix à la journée',
					'name' => 'boat_price_for_full_day',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '€ HT',
					'parent_repeater' => 'field_69ab1839de932',
				),
			),
		),
		array(
			'key' => 'field_69ab06e96adfc',
			'label' => 'Équipements & Options',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69ab07176adfd',
			'label' => 'Équipements inclus',
			'name' => 'boat_equipment_included',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'boat_equipment',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_69ab07486adfe',
			'label' => 'Services inclus',
			'name' => 'boat_services_included',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'boat_equipment',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_69ab07576adff',
			'label' => 'Options sur demande',
			'name' => 'boat_option_on_demand',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'boat_equipment',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boat',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_bt_experience_details',
	'title' => 'Expérience — Détails',
	'fields' => array(
		array(
			'key' => 'field_bt_exp_tab_identity',
			'label' => 'Identité',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_bt_exp_tagline',
			'label' => 'Accroche courte',
			'name' => 'exp_tagline',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Ex: Explorez les calanques de l\'Estérel en 3h',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => 120,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_exp_description',
			'label' => 'Description',
			'name' => 'exp_description',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Description complète de l\'expérience',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_bt_exp_cover',
			'label' => 'Photo principale',
			'name' => 'exp_cover',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_bt_exp_gallery',
			'label' => 'Galerie photos',
			'name' => 'exp_gallery',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'mime_types' => '',
			'insert' => 'append',
			'preview_size' => 'medium',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
		),
		array(
			'key' => 'field_bt_exp_tab_logistics',
			'label' => 'Logistique',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_bt_exp_departure_point',
			'label' => 'Point de départ / arrivé',
			'name' => 'exp_departure_point',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Ex: Port de la Napoule, Quai B',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'city',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_bt_exp_departure_coords',
			'label' => 'Coordonnées GPS départ (port)',
			'name' => 'exp_departure_coords',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Ex: 43.5125, 6.9487',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '43.5125, 6.9487',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_exp_departure_times',
			'label' => 'Horaires de départ',
			'name' => 'exp_departure_times',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Ajouter chaque horaire disponible',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'button_label' => 'Ajouter un horaire',
			'min' => 0,
			'max' => 0,
			'rows_per_page' => 20,
			'collapsed' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_bt_exp_dep_time',
					'label' => 'Heure',
					'name' => 'time',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placeholder' => '09:00',
					'default_value' => '',
					'maxlength' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_bt_exp_departure_times',
				),
				array(
					'key' => 'field_bt_exp_dep_season',
					'label' => 'Saison',
					'name' => 'season',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'all' => 'Toute l\'année',
						'summer' => 'Été (juin–sept)',
						'offseason' => 'Hors saison',
					),
					'default_value' => 'all',
					'return_format' => 'value',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'parent_repeater' => 'field_bt_exp_departure_times',
				),
			),
		),
		array(
			'key' => 'field_bt_exp_pax_min',
			'label' => 'Participants minimum',
			'name' => 'exp_pax_min',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Nombre minimum pour confirmer la sortie',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'min' => 1,
			'max' => 100,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'pax',
		),
		array(
			'key' => 'field_bt_exp_pax_max',
			'label' => 'Participants maximum',
			'name' => 'exp_pax_max',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 1,
			'max' => 200,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'pax',
		),
		array(
			'key' => 'field_bt_exp_languages',
			'label' => 'Langues parlées',
			'name' => 'exp_languages',
			'aria-label' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'fr' => 'Français',
				'en' => 'English',
				'it' => 'Italiano',
			),
			'default_value' => array(
				0 => 'fr',
			),
			'return_format' => 'value',
			'layout' => 'horizontal',
			'toggle' => 0,
			'allow_custom' => 0,
			'save_custom' => 0,
			'custom_choice_button_text' => 'Add new choice',
		),
		array(
			'key' => 'field_bt_exp_tab_pricing',
			'label' => 'Tarification',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69ac75e91c7d3',
			'label' => 'Tarification par forfait',
			'name' => 'tarification_par_forfait',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_bt_exp_price_adult',
					'label' => 'Prix excursion par pers.',
					'name' => 'exp_price',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => 'Prix exact affiché sur la fiche',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'step' => 1,
					'prepend' => '',
					'append' => '€',
					'parent_repeater' => 'field_69ac75e91c7d3',
				),
				array(
					'key' => 'field_69ac76361c7d4',
					'label' => 'Durée de l\'excursion',
					'name' => 'exp_time',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'category',
					'add_term' => 1,
					'save_terms' => 0,
					'load_terms' => 0,
					'return_format' => 'id',
					'field_type' => 'checkbox',
					'allow_in_bindings' => 0,
					'bidirectional' => 0,
					'multiple' => 0,
					'allow_null' => 0,
					'bidirectional_target' => array(
					),
					'parent_repeater' => 'field_69ac75e91c7d3',
				),
				array(
					'key' => 'field_bt_exp_pricing_note',
					'label' => 'Note tarifaire',
					'name' => 'exp_pricing_note',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69ac75e91c7d3',
				),
				array(
					'key' => 'field_bt_exp_deposit',
					'label' => 'Acompte (€)',
					'name' => 'exp_deposit',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'step' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '€',
					'max' => '',
					'parent_repeater' => 'field_69ac75e91c7d3',
				),
			),
		),
		array(
			'key' => 'field_bt_exp_tab_content',
			'label' => 'Contenu & Inclus',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_bt_exp_included',
			'label' => 'Ce qui est inclus',
			'name' => 'exp_included',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Liste de ce qui est fourni : équipement, boissons, skipper…',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'exp-whats-included',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_bt_exp_to_bring',
			'label' => 'Ce qui est exclus',
			'name' => 'exp_to_excluded',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Ce que le client doit apporter',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'whats-excluded',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_69ac6fc043735',
			'label' => 'A apporter',
			'name' => 'exp_to_bring',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Ce que le client doit apporter',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'exp-material-to-bring',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_69ac73f04a902',
			'label' => 'Informations supplémentaires',
			'name' => 'exp_complementary_informations',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Ce que le client doit apporter',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_69ac741e4a903',
			'label' => 'Conseils et conditions',
			'name' => 'exp_advices_conditions',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Ce que le client doit apporter',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_bt_exp_itinerary',
			'label' => 'Programme / Itinéraire',
			'name' => 'exp_itinerary',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Déroulé de l\'excursion étape par étape',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'button_label' => 'Ajouter une étape',
			'min' => 0,
			'max' => 0,
			'rows_per_page' => 20,
			'collapsed' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_bt_exp_itin_time',
					'label' => 'Heure / Moment',
					'name' => 'step_time',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'placeholder' => '09:00',
					'default_value' => '',
					'maxlength' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_bt_exp_itinerary',
				),
				array(
					'key' => 'field_bt_exp_itin_title',
					'label' => 'Titre étape',
					'name' => 'step_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'placeholder' => 'Départ du port',
					'default_value' => '',
					'maxlength' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_bt_exp_itinerary',
				),
				array(
					'key' => 'field_bt_exp_itin_desc',
					'label' => 'Description',
					'name' => 'step_desc',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'rows' => 2,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_bt_exp_itinerary',
				),
			),
		),
		array(
			'key' => 'field_bt_exp_tab_relations',
			'label' => 'Relations',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_bt_exp_boats',
			'label' => 'Bateau(x) utilisé(s)',
			'name' => 'exp_boats',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => 'Lier un ou plusieurs bateaux à cette expérience',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'boat',
			),
			'taxonomy' => array(
			),
			'filters' => array(
				0 => 'search',
			),
			'return_format' => 'object',
			'min' => 0,
			'max' => 0,
			'elements' => array(
				0 => 'featured_image',
			),
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_bt_exp_destinations_rel',
			'label' => 'Destination et départ',
			'name' => 'exp_destinations',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Lier aux pages destination (post type destination)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'city',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_bt_exp_tab_seo',
			'label' => 'SEO & Conversion',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_bt_exp_faq',
			'label' => 'FAQ (Schema FAQPage)',
			'name' => 'exp_faq',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Questions fréquentes — utilisées pour le Schema.org FAQPage',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'button_label' => 'Ajouter une question',
			'min' => 0,
			'max' => 0,
			'rows_per_page' => 20,
			'collapsed' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_bt_exp_faq_q',
					'label' => 'Question',
					'name' => 'faq_question',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_bt_exp_faq',
				),
				array(
					'key' => 'field_bt_exp_faq_a',
					'label' => 'Réponse',
					'name' => 'faq_answer',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '60',
						'class' => '',
						'id' => '',
					),
					'rows' => 3,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_bt_exp_faq',
				),
			),
		),
		array(
			'key' => 'field_69ac6ddaf1af2',
			'label' => 'FAQ (Schema FAQPage) (RelationPage)',
			'name' => 'exp_faq',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => 'Questions fréquentes — utilisées pour le Schema.org FAQPage',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'faq',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_bt_exp_reviews',
			'label' => 'Avis mis en avant',
			'name' => 'exp_reviews_highlight',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Avis clients à afficher sur la page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'button_label' => 'Ajouter un avis',
			'min' => 0,
			'max' => 5,
			'rows_per_page' => 20,
			'collapsed' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_bt_exp_rev_name',
					'label' => 'Prénom',
					'name' => 'rev_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_bt_exp_reviews',
				),
				array(
					'key' => 'field_bt_exp_rev_rating',
					'label' => 'Note /5',
					'name' => 'rev_rating',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'min' => 1,
					'max' => 5,
					'step' => 1,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_bt_exp_reviews',
				),
				array(
					'key' => 'field_bt_exp_rev_text',
					'label' => 'Texte',
					'name' => 'rev_text',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '65',
						'class' => '',
						'id' => '',
					),
					'rows' => 2,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_bt_exp_reviews',
				),
			),
		),
		array(
			'key' => 'field_bt_exp_booking_url',
			'label' => 'UUID Système de réservation Forfait Trajet court',
			'name' => 'exp_booking_short_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Lien vers Fareharbor, Checkfront ou autre',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69ac6dc6f1af1',
			'label' => 'UUID Système de réservation Forfait Trajet Long',
			'name' => 'exp_booking_long_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Lien vers Fareharbor, Checkfront ou autre',
			'required' => false,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'excursion',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_69a6c71b4ee0c',
	'title' => 'FAQ Fields',
	'fields' => array(
		array(
			'key' => 'field_69a6c71e81a04',
			'label' => 'faq_description',
			'name' => 'faq_description',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_69a6c72981a05',
			'label' => 'Est visible sur le booking/diagnostique',
			'name' => 'faq_isforbooking',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
			'ui' => 1,
		),
		array(
			'key' => 'field_69aaa0c330673',
			'label' => 'Catégorie de service liée',
			'name' => 'faq_service_cat',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'service-cat',
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 1,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'faq',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_69ab1cb3307a5',
	'title' => 'Taxomonies Field\'s',
	'fields' => array(
		array(
			'key' => 'field_69ab1cb3a00d1',
			'label' => 'Taxomonies Icons',
			'name' => 'taxomonies_icons',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_69ac76d663b74',
			'label' => 'Taxomonies description',
			'name' => '',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_bt_boat_type_tax',
	'title' => 'Type de bateau — Champs taxonomie',
	'fields' => array(
		array(
			'key' => 'field_bt_boat_type_icon',
			'label' => 'Icône (emoji ou classe)',
			'name' => 'boat_type_icon',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Ex: ⚓ ou fa-ship',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_boat_type_desc',
			'label' => 'Description courte',
			'name' => 'boat_type_desc',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Utilisée dans les filtres et les archives',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'rows' => 2,
			'default_value' => '',
			'placeholder' => '',
			'new_lines' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'boat_type',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_bt_departure_city_tax',
	'title' => 'Ville de départ — Champs taxonomie',
	'fields' => array(
		array(
			'key' => 'field_bt_city_port_name',
			'label' => 'Nom du port',
			'name' => 'city_port_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Ex: Port de la Napoule',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_city_seo_intro',
			'label' => 'Texte SEO intro',
			'name' => 'city_seo_intro',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Texte unique pour la page d\'archive /excursions/cannes/',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_bt_city_address',
			'label' => 'Adresse du port',
			'name' => 'city_address',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Adresse complète pour Schema.org et Google Maps',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_city_coords',
			'label' => 'Coordonnées GPS',
			'name' => 'city_coords',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Ex: 43.5481, 6.9477',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '43.5481, 6.9477',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_city_photo',
			'label' => 'Photo du port',
			'name' => 'city_photo',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => 'Photo authentique du port, pas de stock',
			'required' => false,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'insert' => 'append',
			'library' => 'all',
			'min' => 0,
			'max' => 0,
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_bt_city_parking',
			'label' => 'Info parking',
			'name' => 'city_parking',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Ex: Parking gratuit 200m · Parking payant sur place',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_city_transport',
			'label' => 'Accès transport',
			'name' => 'city_transport',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Ex: Bus ligne 21 · Tramway arrêt Port',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_bt_city_faq',
			'label' => 'FAQ locale',
			'name' => 'city_faq',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Questions spécifiques à ce port de départ',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'button_label' => 'Ajouter une question',
			'min' => 0,
			'max' => 0,
			'rows_per_page' => 20,
			'collapsed' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_bt_city_faq_q',
					'label' => 'Question',
					'name' => 'faq_question',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_bt_city_faq',
				),
				array(
					'key' => 'field_bt_city_faq_a',
					'label' => 'Réponse',
					'name' => 'faq_answer',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '60',
						'class' => '',
						'id' => '',
					),
					'rows' => 2,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_bt_city_faq',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'city',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'boat_capacity', array(
	0 => 'boat',
), array(
	'labels' => array(
		'name' => 'Capacités',
		'singular_name' => 'Capacité',
		'menu_name' => 'Capacité',
		'all_items' => 'All Capacité',
		'edit_item' => 'Edit Capacité',
		'view_item' => 'View Capacité',
		'update_item' => 'Update Capacité',
		'add_new_item' => 'Add New Capacité',
		'new_item_name' => 'New Capacité Name',
		'search_items' => 'Search Capacité',
		'not_found' => 'No capacité found',
		'no_terms' => 'No capacité',
		'items_list_navigation' => 'Capacité list navigation',
		'items_list' => 'Capacité list',
		'back_to_items' => '← Go to capacité',
		'item_link' => 'Capacité Link',
		'item_link_description' => 'A link to a capacité',
	),
	'public' => true,
	'hierarchical' => true,
	'show_ui' => false,
	'show_in_menu' => true,
	'show_in_nav_menus' => false,
	'show_in_rest' => true,
	'show_in_quick_edit' => false,
) );

	register_taxonomy( 'boat_fuel', array(
	0 => 'boat',
), array(
	'labels' => array(
		'name' => 'Carburants',
		'singular_name' => 'Carburant',
		'menu_name' => 'Carburant',
		'all_items' => 'All Carburant',
		'edit_item' => 'Edit Carburant',
		'view_item' => 'View Carburant',
		'update_item' => 'Update Carburant',
		'add_new_item' => 'Add New Carburant',
		'new_item_name' => 'New Carburant Name',
		'parent_item' => 'Parent Carburant',
		'parent_item_colon' => 'Parent Carburant:',
		'search_items' => 'Search Carburant',
		'not_found' => 'No carburant found',
		'no_terms' => 'No carburant',
		'filter_by_item' => 'Filter by carburant',
		'items_list_navigation' => 'Carburant list navigation',
		'items_list' => 'Carburant list',
		'back_to_items' => '← Go to carburant',
		'item_link' => 'Carburant Link',
		'item_link_description' => 'A link to a carburant',
	),
	'public' => true,
	'hierarchical' => true,
	'show_ui' => false,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_tagcloud' => true,
	'show_in_quick_edit' => true,
	'rewrite' => array(
		'hierarchical' => true,
	),
) );

	register_taxonomy( 'exp-material-to-bring', array(
	0 => 'excursion',
), array(
	'labels' => array(
		'name' => 'Ce que vous devez apporter',
		'singular_name' => 'Ce que vous devez apporter',
		'menu_name' => 'Ce que vous devez apporter',
		'all_items' => 'All Ce que vous devez apporter',
		'edit_item' => 'Edit Ce que vous devez apporter',
		'view_item' => 'View Ce que vous devez apporter',
		'update_item' => 'Update Ce que vous devez apporter',
		'add_new_item' => 'Add New Ce que vous devez apporter',
		'new_item_name' => 'New Ce que vous devez apporter Name',
		'parent_item' => 'Parent Ce que vous devez apporter',
		'parent_item_colon' => 'Parent Ce que vous devez apporter:',
		'search_items' => 'Search Ce que vous devez apporter',
		'not_found' => 'No ce que vous devez apporter found',
		'no_terms' => 'No ce que vous devez apporter',
		'filter_by_item' => 'Filter by ce que vous devez apporter',
		'items_list_navigation' => 'Ce que vous devez apporter list navigation',
		'items_list' => 'Ce que vous devez apporter list',
		'back_to_items' => '← Go to ce que vous devez apporter',
		'item_link' => 'Ce que vous devez apporter Link',
		'item_link_description' => 'A link to a ce que vous devez apporter',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'rewrite' => array(
		'hierarchical' => true,
	),
	'sort' => true,
) );

	register_taxonomy( 'exp_duration', array(
	0 => 'excursion',
), array(
	'labels' => array(
		'name' => 'Durées',
		'singular_name' => 'Durée',
		'menu_name' => 'Durée',
		'all_items' => 'All Durée',
		'edit_item' => 'Edit Dur',
		'view_item' => 'View Dur',
		'update_item' => 'Update Dur',
		'add_new_item' => 'Add New Dur',
		'new_item_name' => 'New Dur Name',
		'parent_item' => 'Parent Dur',
		'parent_item_colon' => 'Parent Dur:',
		'search_items' => 'Search Durée',
		'not_found' => 'No durée found',
		'no_terms' => 'No durée',
		'filter_by_item' => 'Filter by dur',
		'items_list_navigation' => 'Durée list navigation',
		'items_list' => 'Durée list',
		'back_to_items' => '← Go to durée',
		'item_link' => 'Dur Link',
		'item_link_description' => 'A link to a dur',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'sort' => true,
) );

	register_taxonomy( 'boat_equipment', array(
	0 => 'boat',
), array(
	'labels' => array(
		'name' => 'Équipements',
		'singular_name' => 'Équipement',
		'menu_name' => 'Équipements',
		'all_items' => 'All Équipements',
		'edit_item' => 'Edit Équipement',
		'view_item' => 'View Équipement',
		'update_item' => 'Update Équipement',
		'add_new_item' => 'Add New Équipement',
		'new_item_name' => 'New Équipement Name',
		'search_items' => 'Search Équipements',
		'not_found' => 'No équipements found',
		'no_terms' => 'No équipements',
		'items_list_navigation' => 'Équipements list navigation',
		'items_list' => 'Équipements list',
		'back_to_items' => '← Go to équipements',
		'item_link' => 'Équipement Link',
		'item_link_description' => 'A link to a équipement',
	),
	'public' => true,
	'hierarchical' => true,
	'show_ui' => false,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_tagcloud' => true,
	'show_in_quick_edit' => true,
) );

	register_taxonomy( 'exigence', array(
	0 => 'excursion',
), array(
	'labels' => array(
		'name' => 'Exigences ',
		'singular_name' => 'Exigence',
		'menu_name' => 'Exigences ',
		'all_items' => 'All Exigences ',
		'edit_item' => 'Edit Exigence',
		'view_item' => 'View Exigence',
		'update_item' => 'Update Exigence',
		'add_new_item' => 'Add New Exigence',
		'new_item_name' => 'New Exigence Name',
		'parent_item' => 'Parent Exigence',
		'parent_item_colon' => 'Parent Exigence:',
		'search_items' => 'Search Exigences ',
		'not_found' => 'No exigences	found',
		'no_terms' => 'No exigences ',
		'filter_by_item' => 'Filter by exigence',
		'items_list_navigation' => 'Exigences	list navigation',
		'items_list' => 'Exigences	list',
		'back_to_items' => '← Go to exigences ',
		'item_link' => 'Exigence Link',
		'item_link_description' => 'A link to a exigence',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'rewrite' => array(
		'hierarchical' => true,
	),
	'sort' => true,
) );

	register_taxonomy( 'boat_length', array(
	0 => 'boat',
), array(
	'labels' => array(
		'name' => 'Largeurs',
		'singular_name' => 'Largeur',
		'menu_name' => 'Largeurs',
		'all_items' => 'All Largeurs',
		'edit_item' => 'Edit Largeur',
		'view_item' => 'View Largeur',
		'update_item' => 'Update Largeur',
		'add_new_item' => 'Add New Largeur',
		'new_item_name' => 'New Largeur Name',
		'parent_item' => 'Parent Largeur',
		'parent_item_colon' => 'Parent Largeur:',
		'search_items' => 'Search Largeurs',
		'not_found' => 'No largeurs found',
		'no_terms' => 'No largeurs',
		'filter_by_item' => 'Filter by largeur',
		'items_list_navigation' => 'Largeurs list navigation',
		'items_list' => 'Largeurs list',
		'back_to_items' => '← Go to largeurs',
		'item_link' => 'Largeur Link',
		'item_link_description' => 'A link to a largeur',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'sort' => true,
) );

	register_taxonomy( 'boat_thickness', array(
	0 => 'boat',
), array(
	'labels' => array(
		'name' => 'Longueurs',
		'singular_name' => 'Longueur',
		'menu_name' => 'Longueurs',
		'all_items' => 'All Longueurs',
		'edit_item' => 'Edit Longueur',
		'view_item' => 'View Longueur',
		'update_item' => 'Update Longueur',
		'add_new_item' => 'Add New Longueur',
		'new_item_name' => 'New Longueur Name',
		'parent_item' => 'Parent Longueur',
		'parent_item_colon' => 'Parent Longueur:',
		'search_items' => 'Search Longueurs',
		'not_found' => 'No longueurs found',
		'no_terms' => 'No longueurs',
		'filter_by_item' => 'Filter by longueur',
		'items_list_navigation' => 'Longueurs list navigation',
		'items_list' => 'Longueurs list',
		'back_to_items' => '← Go to longueurs',
		'item_link' => 'Longueur Link',
		'item_link_description' => 'A link to a longueur',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'sort' => true,
) );

	register_taxonomy( 'boat_skipper', array(
	0 => 'boat',
), array(
	'labels' => array(
		'name' => 'Skippers',
		'singular_name' => 'Skipper',
		'menu_name' => 'Skipper',
		'all_items' => 'All Skipper',
		'edit_item' => 'Edit Skipper',
		'view_item' => 'View Skipper',
		'update_item' => 'Update Skipper',
		'add_new_item' => 'Add New Skipper',
		'new_item_name' => 'New Skipper Name',
		'search_items' => 'Search Skipper',
		'not_found' => 'No skipper found',
		'no_terms' => 'No skipper',
		'items_list_navigation' => 'Skipper list navigation',
		'items_list' => 'Skipper list',
		'back_to_items' => '← Go to skipper',
		'item_link' => 'Skipper Link',
		'item_link_description' => 'A link to a skipper',
	),
	'public' => true,
	'hierarchical' => true,
	'show_ui' => false,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_tagcloud' => true,
	'show_in_quick_edit' => true,
) );

	register_taxonomy( 'experience_price_range', array(
	0 => 'experience',
), array(
	'labels' => array(
		'name' => 'Tranches de prix',
		'singular_name' => 'Tranche de prix',
		'menu_name' => 'Tranches de prix',
		'all_items' => 'All Tranches de prix',
		'edit_item' => 'Edit Tranche de prix',
		'view_item' => 'View Tranche de prix',
		'update_item' => 'Update Tranche de prix',
		'add_new_item' => 'Add New Tranche de prix',
		'new_item_name' => 'New Tranche de prix Name',
		'parent_item' => 'Parent Tranche de prix',
		'parent_item_colon' => 'Parent Tranche de prix:',
		'search_items' => 'Search Tranches de prix',
		'not_found' => 'No tranches de prix found',
		'no_terms' => 'No tranches de prix',
		'filter_by_item' => 'Filter by tranche de prix',
		'items_list_navigation' => 'Tranches de prix list navigation',
		'items_list' => 'Tranches de prix list',
		'back_to_items' => '← Go to tranches de prix',
		'item_link' => 'Tranche de prix Link',
		'item_link_description' => 'A link to a tranche de prix',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );

	register_taxonomy( 'experience_type', array(
	0 => 'experience',
), array(
	'labels' => array(
		'name' => 'Types d\'expériences',
		'singular_name' => 'Type d\'expérience',
		'menu_name' => 'Type d\'expérience',
		'all_items' => 'All Type d\'expérience',
		'edit_item' => 'Edit Type d\'expérience',
		'view_item' => 'View Type d\'expérience',
		'update_item' => 'Update Type d\'expérience',
		'add_new_item' => 'Add New Type d\'expérience',
		'new_item_name' => 'New Type d\'expérience Name',
		'search_items' => 'Search Type d\'expérience',
		'popular_items' => 'Popular Type d\'expérience',
		'separate_items_with_commas' => 'Separate type d\'expérience with commas',
		'add_or_remove_items' => 'Add or remove type d\'expérience',
		'choose_from_most_used' => 'Choose from the most used type d\'expérience',
		'not_found' => 'No type d\'expérience found',
		'no_terms' => 'No type d\'expérience',
		'items_list_navigation' => 'Type d\'expérience list navigation',
		'items_list' => 'Type d\'expérience list',
		'back_to_items' => '← Go to type d\'expérience',
		'item_link' => 'Type d\'expérience Link',
		'item_link_description' => 'A link to a type d\'expérience',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );

	register_taxonomy( 'type-de-bateau', array(
	0 => 'boat',
), array(
	'labels' => array(
		'name' => 'Types de bateau',
		'singular_name' => 'Type de bateau',
		'menu_name' => 'Types de bateau',
		'all_items' => 'All Types de bateau',
		'edit_item' => 'Edit Type de bateau',
		'view_item' => 'View Type de bateau',
		'update_item' => 'Update Type de bateau',
		'add_new_item' => 'Add New Type de bateau',
		'new_item_name' => 'New Type de bateau Name',
		'parent_item' => 'Parent Type de bateau',
		'parent_item_colon' => 'Parent Type de bateau:',
		'search_items' => 'Search Types de bateau',
		'not_found' => 'No types de bateau found',
		'no_terms' => 'No types de bateau',
		'filter_by_item' => 'Filter by type de bateau',
		'items_list_navigation' => 'Types de bateau list navigation',
		'items_list' => 'Types de bateau list',
		'back_to_items' => '← Go to types de bateau',
		'item_link' => 'Type de bateau Link',
		'item_link_description' => 'A link to a type de bateau',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'sort' => true,
) );

	register_taxonomy( 'city', array(
	0 => '',
), array(
	'labels' => array(
		'name' => 'Villes de départ/Destination',
		'singular_name' => 'Ville de départ/Destination',
		'menu_name' => 'Villes de départ/Destination',
		'all_items' => 'All Villes de départ/Destination',
		'edit_item' => 'Edit Ville de départ/Destination',
		'view_item' => 'View Ville de départ/Destination',
		'update_item' => 'Update Ville de départ/Destination',
		'add_new_item' => 'Add New Ville de départ/Destination',
		'new_item_name' => 'New Ville de départ/Destination Name',
		'parent_item' => 'Parent Ville de départ/Destination',
		'parent_item_colon' => 'Parent Ville de départ/Destination:',
		'search_items' => 'Search Villes de départ/Destination',
		'not_found' => 'No villes de départ/destination found',
		'no_terms' => 'No villes de départ/destination',
		'filter_by_item' => 'Filter by ville de départ/destination',
		'items_list_navigation' => 'Villes de départ/Destination list navigation',
		'items_list' => 'Villes de départ/Destination list',
		'back_to_items' => '← Go to villes de départ/destination',
		'item_link' => 'Ville de départ/Destination Link',
		'item_link_description' => 'A link to a ville de départ/destination',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'rewrite' => array(
		'slug' => 'excursions',
		'hierarchical' => true,
	),
	'sort' => true,
) );

	register_taxonomy( 'whats-excluded', array(
	0 => 'excursion',
), array(
	'labels' => array(
		'name' => 'What\'s excluded',
		'singular_name' => 'What\'s excluded',
		'menu_name' => 'What\'s excluded',
		'all_items' => 'All What\'s excluded',
		'edit_item' => 'Edit What\'s excluded',
		'view_item' => 'View What\'s excluded',
		'update_item' => 'Update What\'s excluded',
		'add_new_item' => 'Add New What\'s excluded',
		'new_item_name' => 'New What\'s excluded Name',
		'parent_item' => 'Parent What\'s excluded',
		'parent_item_colon' => 'Parent What\'s excluded:',
		'search_items' => 'Search What\'s excluded',
		'not_found' => 'No what\'s excluded found',
		'no_terms' => 'No what\'s excluded',
		'filter_by_item' => 'Filter by what\'s excluded',
		'items_list_navigation' => 'What\'s excluded list navigation',
		'items_list' => 'What\'s excluded list',
		'back_to_items' => '← Go to what\'s excluded',
		'item_link' => 'What\'s excluded Link',
		'item_link_description' => 'A link to a what\'s excluded',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'rewrite' => array(
		'hierarchical' => true,
	),
	'sort' => true,
) );

	register_taxonomy( 'exp-whats-included', array(
	0 => 'excursion',
), array(
	'labels' => array(
		'name' => 'What\'s included',
		'singular_name' => 'What\'s included',
		'menu_name' => 'What\'s included',
		'all_items' => 'All What\'s included',
		'edit_item' => 'Edit What\'s included',
		'view_item' => 'View What\'s included',
		'update_item' => 'Update What\'s included',
		'add_new_item' => 'Add New What\'s included',
		'new_item_name' => 'New What\'s included Name',
		'parent_item' => 'Parent What\'s included',
		'parent_item_colon' => 'Parent What\'s included:',
		'search_items' => 'Search What\'s included',
		'not_found' => 'No what\'s included found',
		'no_terms' => 'No what\'s included',
		'filter_by_item' => 'Filter by what\'s included',
		'items_list_navigation' => 'What\'s included list navigation',
		'items_list' => 'What\'s included list',
		'back_to_items' => '← Go to what\'s included',
		'item_link' => 'What\'s included Link',
		'item_link_description' => 'A link to a what\'s included',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'rewrite' => array(
		'hierarchical' => true,
	),
	'sort' => true,
) );
} );

add_action( 'init', function() {
	register_post_type( 'boat', array(
	'labels' => array(
		'name' => 'Boats',
		'singular_name' => 'Boat',
		'menu_name' => 'Boats',
		'all_items' => 'All Boats',
		'edit_item' => 'Edit Boat',
		'view_item' => 'View Boat',
		'view_items' => 'View Boats',
		'add_new_item' => 'Add New Boat',
		'add_new' => 'Add New Boat',
		'new_item' => 'New Boat',
		'parent_item_colon' => 'Parent Boat:',
		'search_items' => 'Search Boats',
		'not_found' => 'No boats found',
		'not_found_in_trash' => 'No boats found in Trash',
		'archives' => 'Boat Archives',
		'attributes' => 'Boat Attributes',
		'insert_into_item' => 'Insert into boat',
		'uploaded_to_this_item' => 'Uploaded to this boat',
		'filter_items_list' => 'Filter boats list',
		'filter_by_date' => 'Filter boats by date',
		'items_list_navigation' => 'Boats list navigation',
		'items_list' => 'Boats list',
		'item_published' => 'Boat published.',
		'item_published_privately' => 'Boat published privately.',
		'item_reverted_to_draft' => 'Boat reverted to draft.',
		'item_scheduled' => 'Boat scheduled.',
		'item_updated' => 'Boat updated.',
		'item_link' => 'Boat Link',
		'item_link_description' => 'A link to a boat.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'https://dev.studiojae.fr/wp-content/uploads/2026/02/ferry-boat-2.png',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
	),
	'has_archive' => true,
	'delete_with_user' => false,
) );

	register_post_type( 'excursion', array(
	'labels' => array(
		'name' => 'Excursions',
		'singular_name' => 'Excursion',
		'menu_name' => 'Excursions',
		'all_items' => 'All Excursions',
		'edit_item' => 'Edit Excursion',
		'view_item' => 'View Excursion',
		'view_items' => 'View Excursions',
		'add_new_item' => 'Add New Excursion',
		'add_new' => 'Add New Excursion',
		'new_item' => 'New Excursion',
		'parent_item_colon' => 'Parent Excursion:',
		'search_items' => 'Search Excursions',
		'not_found' => 'No excursions found',
		'not_found_in_trash' => 'No excursions found in Trash',
		'archives' => 'Excursion Archives',
		'attributes' => 'Excursion Attributes',
		'insert_into_item' => 'Insert into excursion',
		'uploaded_to_this_item' => 'Uploaded to this excursion',
		'filter_items_list' => 'Filter excursions list',
		'filter_by_date' => 'Filter excursions by date',
		'items_list_navigation' => 'Excursions list navigation',
		'items_list' => 'Excursions list',
		'item_published' => 'Excursion published.',
		'item_published_privately' => 'Excursion published privately.',
		'item_reverted_to_draft' => 'Excursion reverted to draft.',
		'item_scheduled' => 'Excursion scheduled.',
		'item_updated' => 'Excursion updated.',
		'item_link' => 'Excursion Link',
		'item_link_description' => 'A link to a excursion.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'https://dev.studiojae.fr/wp-content/uploads/2026/02/port-1.png',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'revisions',
		3 => 'page-attributes',
		4 => 'thumbnail',
		5 => 'custom-fields',
	),
	'taxonomies' => array(
		0 => 'boat_skipper',
		1 => 'city',
		2 => 'experience_type',
		3 => 'experience_price_range',
	),
	'has_archive' => true,
	'delete_with_user' => false,
) );

	register_post_type( 'faq', array(
	'labels' => array(
		'name' => 'FAQs',
		'singular_name' => 'FAQ',
		'menu_name' => 'FAQs',
		'all_items' => 'All FAQs',
		'edit_item' => 'Edit FAQ',
		'view_item' => 'View FAQ',
		'view_items' => 'View FAQs',
		'add_new_item' => 'Add New FAQ',
		'add_new' => 'Add New FAQ',
		'new_item' => 'New FAQ',
		'parent_item_colon' => 'Parent FAQ:',
		'search_items' => 'Search FAQs',
		'not_found' => 'No faqs found',
		'not_found_in_trash' => 'No faqs found in Trash',
		'archives' => 'FAQ Archives',
		'attributes' => 'FAQ Attributes',
		'insert_into_item' => 'Insert into faq',
		'uploaded_to_this_item' => 'Uploaded to this faq',
		'filter_items_list' => 'Filter faqs list',
		'filter_by_date' => 'Filter faqs by date',
		'items_list_navigation' => 'FAQs list navigation',
		'items_list' => 'FAQs list',
		'item_published' => 'FAQ published.',
		'item_published_privately' => 'FAQ published privately.',
		'item_reverted_to_draft' => 'FAQ reverted to draft.',
		'item_scheduled' => 'FAQ scheduled.',
		'item_updated' => 'FAQ updated.',
		'item_link' => 'FAQ Link',
		'item_link_description' => 'A link to a faq.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );
} );

